core.symlinks=true
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
user.name=raza
user.email=rajaliraza@yahoo.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=https://www.github.com/rajaliraza1/Web-development.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.upstream.url=https://github.com/rajaliraza1/Web-development.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.origin-push.url=https://www.github.com/rajaliraza1/Web-development.git
remote.origin-push.fetch=+refs/heads/*:refs/remotes/origin-push/*
